<?php

namespace Tests\LaravelFacebookAds;

use Orchestra\Testbench\TestCase;
use Edbizarro\LaravelFacebookAds\FacebookAds;
use Edbizarro\LaravelFacebookAds\Providers\LaravelFacebookServiceProvider;

/**
 * Class BaseTest.
 */
abstract class BaseTest extends TestCase
{
    /**
     * @var FacebookAds
     */
    protected $laravelFacebookAds;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->laravelFacebookAds = $this->app[\Edbizarro\LaravelFacebookAds\FacebookAds::class];
    }

    /**
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return [LaravelFacebookServiceProvider::class];
    }
}
